[package]
name = "demo"
version = "0.1.0"
authors = ["zhuyadong"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.11.1"
actix-rt = "2.2.0"
